name: ci

on:
  push:
    branches-ignore:
      - "master"
      - "develop"
  pull_request:

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 12, 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm t -- --runInBand --ci --bail
