name: release-version

on:
  push:
    tags:
      - v*.*.*

jobs:
  release-version:
    name: release-version
    strategy:
      matrix:
        os: [ ubuntu-20.04, macOs-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm t -- --runInBand --ci --bail
      - name: publish packages
        if: runner.os == 'Linux'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}